---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Subnet:
    Description: "Select the Subnets ID for Instance creation "
    Type: "AWS::EC2::Subnet::Id"

  VPCAdminSecurityGroup:
    Description: "Select Admin VPC security groups"
    Type: AWS::EC2::SecurityGroup::Id

  VPCEC2SecurityGroup:
    Description: "Select EC2 VPC security groups"
    Type: AWS::EC2::SecurityGroup::Id

  KeyName:
     Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance"
     Type: "AWS::EC2::KeyPair::KeyName"

  InstanceType:
      Description: "EC2 instance type"
      Type: String
      Default: "t2.micro"
      AllowedValues:
        - "t1.micro"
        - "t2.micro"
        - "t2.small"

Mappings:
  AWSRegionAMI:
    us-east-1:
      AMI: "ami-04681a1dbd79675a5"
    us-east-2:
      AMI: "ami-0cf31d971a3ca20d6"
    us-west-1:
      AMI: "ami-0782017a917e973e7"
    us-west-2:
      AMI: "ami-6cd6f714"

Resources:

  AnsIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  AnsInstanceProfile:
    Description: "Profile for Ansible Instance"
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref AnsIAMRole

  WEBInstance:
    Description: "Instance with WEB server"
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [AWSRegionAMI, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref AnsInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref VPCAdminSecurityGroup
            - !Ref VPCEC2SecurityGroup
          SubnetId:
            Ref: Subnet
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash
            set -e
            sudo yum update -y
            cd ~/.ssh/
            sudo wget https://github.com/hdgdink/MPAWS/tree/master/resources/ansKey.pub
            echo anskey.pub >> authorized_keys
      Tags:
        -
          Key: Name
          Value: "WEB"

  DBInstance:
    Description: "Instance with MySQL server"
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [AWSRegionAMI, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref AnsInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref VPCAdminSecurityGroup
            - !Ref VPCEC2SecurityGroup
          SubnetId:
            Ref: Subnet
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash
            set -e
            sudo yum update -y
            cd ~/.ssh/
            sudo wget https://github.com/hdgdink/MPAWS/tree/master/resources/ansKey.pub
            echo anskey.pub >> authorized_keys
      Tags:
        -
          Key: Name
          Value: "Db"

  AnsibleInstance:
    Description: "Control instance with Ansible"
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [AWSRegionAMI, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref AnsInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref VPCAdminSecurityGroup
            - !Ref VPCEC2SecurityGroup
          SubnetId:
            Ref: Subnet
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash

            set -e

            sudo yum update -y
            sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
            sudo pip install ansible
            sudo pip install boto
            cd ~
            sudo wget https://raw.githubusercontent.com/hdgdink/MPAWS/master/resources/ansKey
            sudo wget https://raw.githubusercontent.com/hdgdink/MPAWS/master/resources/ansKey.pub
            cd /etc/ansible/
            sudo wget https://raw.githubusercontent.com/hdgdink/MPAWS/master/resources/ec2.ini
            sudo wget https://raw.githubusercontent.com/hdgdink/MPAWS/master/resources/ec2.py
            sudo chmod +x /etc/ansible/ec2.py
            sudo wget https://raw.githubusercontent.com/hdgdink/MPAWS/master/resources/Ansible/ansible.cfg
            sudo wget https://raw.githubusercontent.com/hdgdink/MPAWS/master/resources/Ansible/myhosts
      Tags:
        -
          Key: Name
          Value: "Ansible"